### ISSUE TITLE
Password for moddle VM

### ISSUE THREAD

**Issue by nishant2019** [crond-jaist/cytrone#1]
user@192.168.122.232: Permission denied (publickey,password).
root@192.168.122.232 (Moodle VM) password can be found in user guide.
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 3 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@192.168.122.232's password: 
Permission denied, please try again.
root@192.168.122.232's password: 

What is the password  ???

**Comment by athna** [comment]
Where were you downloaded from moodleVM?
If you downloaded moodleVM from CyLMS release page ,password is written in CyLMS's user guide (cylms-1.1-guide.pdf) page 20 ( page number that printed at user guide is 16) , chapter 3. UTILIZATION , Section 3.2  MoodleSetup , 3.2.1 Initial VM settings.
